apiVersion: v1
kind: Pod
metadata:
  labels:
    run: helloworld
  name: helloworld
  namespace: default
spec:
  containers:
  - image: hello-world
    name: helloworld
  dnsPolicy: ClusterFirst
  restartPolicy: Never
